export const data = [
  {
    img: "https://randomuser.me/api/portraits/women/1.jpg",
    name: "John Doe",
    userId: "123456",
    stories: [
      {
        img: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "A beautiful day!",
      },
      {
        img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Exploring new places",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "John Smith",
    userId: "654321",
    stories: [
      {
        img: "https://cdn.pixabay.com/photo/2016/03/30/08/24/peacock-1290248_1280.jpg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Morning vibes!",
      },
      {
        img: "https://images.unsplash.com/photo-1485217988980-11786ced9454",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Sunset by the beach",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/3.jpg",
    name: "Jane Doe",
    userId: "987654",
    stories: [
      {
        img: "https://images.pexels.com/photos/207962/pexels-photo-207962.jpeg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "City lights",
      },
      {
        img: "https://images.pexels.com/photos/1687830/pexels-photo-1687830.jpeg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Nature's beauty",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Alice Johnson",
    userId: "456789",
    stories: [
      {
        img: "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Adventures await",
      },
      {
        img: "https://images.pexels.com/photos/1921336/pexels-photo-1921336.jpeg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Chasing dreams",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/5.jpg",
    name: "Bob Smith",
    userId: "321654",
    stories: [
      {
        img: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_960_720.jpg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Mountaintop views",
      },
      {
        img: "https://cdn.pixabay.com/photo/2023/09/28/21/22/highland-cattle-8282564_1280.jpg",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "In the moment",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Emily Brown",
    userId: "789123",
    stories: [
      {
        img: "https://plus.unsplash.com/premium_photo-1686779700540-9537b63e1a8f",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Hiking adventures",
      },
      {
        img: "https://plus.unsplash.com/premium_photo-1701192455496-a095e6e5f792",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Cityscape",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/7.jpg",
    name: "David Wilson",
    userId: "456123",
    stories: [
      {
        img: "https://images.unsplash.com/photo-1719937206491-ed673f64be1f",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Forest trails",
      },
      {
        img: "https://images.unsplash.com/photo-1721297014355-bea6467bb1c9",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Golden hour",
      },
    ],
  },
  {
    img: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Olivia Davis",
    userId: "987321",
    stories: [
      {
        img: "https://images.unsplash.com/photo-1721150641805-23a37065c116",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Mountain escape",
      },
      {
        img: "https://plus.unsplash.com/premium_photo-1706800175843-795bc59419e6",
        viewed: false,
        viewedAt: null,
        timestamp: Date.now(),
        mediaType: "image",
        duration: 10,
        caption: "Sunrise moments",
      },
    ],
  },
];
